enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "apk"
version = "auto"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"


[Music-anddea]
enabled = true
app-name = "Music"
version = "latest"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "apk"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Extended]
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "Music ReVanced Extended"
build-mode = "apk"
excluded-patches = "custom-branding-icon-revancify-blue"
included-patches = "custom-branding-icon-mmt"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"                                                  # both arm64-v8a and arm-v7a

[YouTube-Extended]
build-mode = "both"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "Youtube ReVanced Advanced"
build-mode = "apk"
excluded-patches = "custom-branding-icon-revancify-blue"
included-patches = "custom-branding-icon-mmt"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

